spring:

  profiles:
    active: dev #默认为开发环境




mybatis-plus:
  configuration:
    #??????????????????????????????????????? address_book ---> AddressBook
    map-underscore-to-camel-case: true

    #????
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto
  mapper-locations: classpath:/mapper/*.xml #?? xml????

aliyun:
  oss:
    endpoint: oss-cn-hangzhou.aliyuncs.com
    accessKeyId: LTAI5t6tVFa9QTsHAGCGVUa3
    accessKeySecret: QD3CFUrUGP4KsC0ZNldfUXnpa08InI
    bucketName: mall-bucket12
    imgUrl: product